# This is a basic workflow to help you get started with Actions

name: Build a notebook

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      LABS:
        description: 'Labs version'
        required: true
        default: 'v2'
        type: string
      ID:
        description: 'Which lab to build'
        required: true
        default: '03'
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      # Install
      - name: Install dependencies 
        run: |
          pip install .
          pip install jupyterlab

      # Runs a set of commands using the runners shell
      - name: Build notebook 
        env:
          LABS:  ${{ inputs.LABS }}
          ID:  ${{ inputs.ID }}
        run: |
          git clone https://github.com/intro-stat-learning/ISLP_labs.git
          cd ISLP_labs
          git checkout $LABS
          cp Ch*$ID*lab.ipynb ..
          jupyter nbconvert --execute --inplace ../Ch*$ID*lab.ipynb 
          jupyter nbconvert --to html ../Ch*$ID*lab.ipynb 

      # Store the output
      - name: Upload labs
        env:
          ID:  ${{ inputs.ID }}
        uses: actions/upload-artifact@v3
        with:
          name: ISLP_labs
          path: Ch*
          retention-days: 1

  build-mac:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      # Install
      - name: Install dependencies 
        run: |
          pip install .
          pip install jupyterlab

      # Runs a set of commands using the runners shell
      - name: Build notebook 
        env:
          LABS:  ${{ inputs.LABS }}
          ID:  ${{ inputs.ID }}
        run: |
          git clone https://github.com/intro-stat-learning/ISLP_labs.git
          cd ISLP_labs
          git checkout $LABS
          cp Ch*$ID*lab.ipynb ..
          jupyter nbconvert --execute --inplace ../Ch*$ID*lab.ipynb 
          jupyter nbconvert --to html ../Ch*$ID*lab.ipynb 

      # Store the output
      - name: Upload labs
        env:
          ID:  ${{ inputs.ID }}
        uses: actions/upload-artifact@v3
        with:
          name: ISLP_labs
          path: Ch*
          retention-days: 1