# This is a basic workflow to help you get started with Actions

name: Build + save notebooks (not 10,13)

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      LABS:
        description: 'Labs version'
        required: true
        default: 'v2'
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      # Install
      - name: Install dependencies 
        run: |
          pip install .

      # Runs a set of commands using the runners shell
      - name: Build Ch02 notebook (allow errors)
        env:
          LABS:  ${{ inputs.LABS }}
        run: |
          git clone https://github.com/intro-stat-learning/ISLP_labs.git
          cd ISLP_labs
          git checkout $LABS
          rm Ch10*
          rm Ch13*
          jupyter nbconvert --execute --inplace --allow-errors Ch02*lab.ipynb 

      - name: Build Ch03 notebook
        run: |
          cd ISLP_labs
          jupyter nbconvert --execute --inplace  Ch03*lab.ipynb 

      - name: Build Ch04 notebook
        run: |
          cd ISLP_labs
          jupyter nbconvert --execute --inplace  Ch04*lab.ipynb 

      - name: Build Ch05 notebook
        run: |
          cd ISLP_labs
          jupyter nbconvert --execute --inplace  Ch05*lab.ipynb 

      - name: Build Ch06 notebook
        run: |
          cd ISLP_labs
          jupyter nbconvert --execute --inplace  Ch06*lab.ipynb 

      - name: Build Ch07 notebook
        run: |
          cd ISLP_labs
          jupyter nbconvert --execute --inplace  Ch07*lab.ipynb 

      - name: Build Ch08 notebook
        run: |
          cd ISLP_labs
          jupyter nbconvert --execute --inplace  Ch08*lab.ipynb 

      - name: Build Ch09 notebook
        run: |
          cd ISLP_labs
          jupyter nbconvert --execute --inplace  Ch09*lab.ipynb 

      - name: Build Ch11 notebook
        run: |
          cd ISLP_labs
          jupyter nbconvert --execute --inplace  Ch11*lab.ipynb 

      - name: Build Ch12 notebook
        run: |
          cd ISLP_labs
          jupyter nbconvert --execute --inplace  Ch12*lab.ipynb 

      - name: Build HTML
        run: |
          cd ISLP_labs
          jupyter nbconvert --to html Ch*ipynb 

      # Store the output
      - name: Upload labs
        uses: actions/upload-artifact@v3
        with:
          name: ISLP_labs
          path: Ch*
          retention-days: 1